baseURL: "https://dscrnsitblog.netlify.app/"
languageCode: en-us
title: "DSC RNSIT Blog"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "DSC RNSIT Blog"
    description: "Developer Student Clubs is a Google Developers program for university students to learn mobile and web development skills, design thinking skills and leadership skills."
    keywords: ["DSC RNSIT", Blog, Portfolio, PaperMod]
    author: ["DSC RNSIT"]
    # author: ["Me", "You"] # multiple authors
    images: ["logo.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    assets:
        disableHLJS: false # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
#        safari_pinned_tab: "<link / abs url>"

    label:
        text: "DSC RNSIT Blog"
        icon: /icon.png
        iconHeight: 35

#    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
#        title: ExampleSite
#        subtitle: "This is subtitle"
#        imageUrl: "<img location>"
#        imageWidth: 120
#        imageHeight: 120
#        imageTitle: my image
#        buttons:
#            - name: Posts
#              url: posts
#            - name: Tags
#              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to DSC RNSIT blog. Developer Student Clubs is a Google Developers program for university students to learn mobile and web development skills, design thinking skills and leadership skills.
    
    schema:
        publisherType: "RNS Institute of Technology"

    socialIcons:
        - name: facebook
          url: "https://www.facebook.com/dscrnsit"
        - name: twitter
          url: "https://twitter.com/dscrnsit"
        - name: instagram
          url: "https://instagram.com/dsc_rnsit"
        - name: linkedin
          url: "https://www.linkedin.com/company/dsc-rnsit"
        - name: youtube
          url: "https://www.youtube.com/channel/UC-MB-BSUb7fwWPy99j8xkcA"
        - name: github
          url: "https://github.com/dscrnsit"
        - name: email
          url: "mailto:dscrnsit@gmail.com"

#    analytics:
#        google:
#            SiteVerificationTag: "XYZabc"
#        bing:
#            SiteVerificationTag: "XYZabc"
#        yandex:
#            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/dscrnsit/Blog/tree/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 30
        - identifier: website
          name: dscrnsit.github.io
          url: https://dscrnsit.github.io
          weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

